[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "https://staging3.kimweb.agency/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
